// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","name":"首页","parentId":"@@/global-layout","id":"1"},"2":{"path":"/docs","name":"文档","parentId":"@@/global-layout","id":"2"},"3":{"path":"/demo1","name":"demo1","parentId":"@@/global-layout","id":"3"},"4":{"path":"/storeDemo","name":"storeDemo","parentId":"@@/global-layout","id":"4"},"5":{"path":"/todoList","name":"todoList","parentId":"@@/global-layout","id":"5"},"6":{"path":"/threejs","name":"Threejs","parentId":"@@/global-layout","id":"6"},"7":{"path":"/threejs/basicDemo","name":"basicDemo","parentId":"6","id":"7"},"8":{"path":"/threejs/lineDemo","name":"lineDemo","parentId":"6","id":"8"},"9":{"path":"/threejs/fontDemo","name":"fontDemo","parentId":"6","id":"9"},"10":{"path":"/threejs/3DDemo","name":"3DDemo","parentId":"6","id":"10"},"11":{"path":"/threejs/listDemo","name":"listDemo","parentId":"6","id":"11"},"12":{"path":"/threejs/guiDemo","name":"guiDemo","parentId":"6","id":"12"},"13":{"path":"/threejs/geoDemo","name":"geoDemo","parentId":"6","id":"13"},"14":{"path":"/threejs/modelDemo","name":"modelDemo","parentId":"6","id":"14"},"15":{"path":"/threejs/groupDemo","name":"groupDemo","parentId":"6","id":"15"},"16":{"path":"/threejs/texturesDemo","name":"texturesDemo","parentId":"6","id":"16"},"17":{"path":"/threejs/PBRDemo","name":"PBRDemo","parentId":"6","id":"17"},"18":{"path":"/leetCode","name":"leetCode","parentId":"@@/global-layout","id":"18"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__index" */'@/pages/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__docs" */'@/pages/docs.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__demo1__index" */'@/pages/demo1/index.jsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__storeDemo__index" */'@/pages/storeDemo/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__todoList__index" */'@/pages/todoList/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__threejs__index" */'@/pages/threejs/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__threejs__basicDemo__index" */'@/pages/threejs/basicDemo/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__threejs__lineDemo__index" */'@/pages/threejs/lineDemo/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__threejs__fontDemo__index" */'@/pages/threejs/fontDemo/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__threejs__3DDemo__index" */'@/pages/threejs/3DDemo/index.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__threejs__listDemo__index" */'@/pages/threejs/listDemo/index.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__threejs__guiDemo__index" */'@/pages/threejs/guiDemo/index.tsx')),
'13': React.lazy(() => import(/* webpackChunkName: "p__threejs__geoDemo__index" */'@/pages/threejs/geoDemo/index.tsx')),
'14': React.lazy(() => import(/* webpackChunkName: "p__threejs__modelDemo__index" */'@/pages/threejs/modelDemo/index.tsx')),
'15': React.lazy(() => import(/* webpackChunkName: "p__threejs__groupDemo__index" */'@/pages/threejs/groupDemo/index.tsx')),
'16': React.lazy(() => import(/* webpackChunkName: "p__threejs__texturesDemo__index" */'@/pages/threejs/texturesDemo/index.tsx')),
'17': React.lazy(() => import(/* webpackChunkName: "p__threejs__PBRDemo__index" */'@/pages/threejs/PBRDemo/index.tsx')),
'18': React.lazy(() => import(/* webpackChunkName: "p__leetCode__index" */'@/pages/leetCode/index.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'I:/React学习/myapp/src/layouts/index.tsx')),
},
  };
}
